### ISSUE TITLE
curio is not available for Windows

### ISSUE THREAD

**Issue by mrakitin** [conda-forge/caproto-feedstock#9]
curio is not available on Windows: https://github.com/conda-forge/curio-feedstock/blob/0dc0d251266a669d92c8436c673d2d36e4604f9d/recipe/meta.yaml#L18

Should it be skipped conditionally for this recipe?

attn @CJ-Wright

**Comment by CJ-Wright** [comment]
I think this is not needed, this is noarch. The install will fail on Windows with an error stating that curio is not available.

**Comment by mrakitin** [comment]
It means we won't have the package working on Windows, which may not be what we want, and caproto may not use the library underneath on Windows. Is there a way to conditionally specify the dependencies for noarch packages?

**Comment by CJ-Wright** [comment]
Is curio a hard requirement?

No there is no way to declare conditionals for noarch packages.

**Comment by mrakitin** [comment]
No, all requirements in [caproto](https://github.com/caproto/caproto/blob/3b802c885b4ecb3c9aa70947b86dddbb6aded2c4/setup.py#L36-L40) are optional (cc @danielballan). I wonder why [curio's recipe](https://github.com/conda-forge/curio-feedstock/blob/master/recipe/meta.yaml) is arch-dependent? Its [`setup.py`](https://github.com/dabeaz/curio/blob/master/setup.py) does not have any extensions... Any ideas, @CJ-Wright?

**Comment by CJ-Wright** [comment]
Nope, you could try putting in a PR into curio and seeing if it fails.

Conda doesn't really do optional dependencies, so my advise would be to:
1. See if you can get a windows curio build running, if you can then there is nothing to do here.
2. Remove curio from the requirements of caproto, then this can install on windows no problem and if people want curio then they can install it themselves.

**Comment by mrakitin** [comment]
We just made it work for Windows with @buijennifer via https://github.com/nsls-ii-forge/curio-feedstock. See the latest Azure builds here: https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=150. We limited the full suite of tests to run on Linux only, as it failed on Windows/OSX.

**Comment by CJ-Wright** [comment]
Why did it fail on windows?

**Comment by mrakitin** [comment]
I think it failed for the same reason as in https://github.com/conda-forge/staged-recipes/pull/2104. See e.g. https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.9954/job/527unam00cy6wwfi#L473 for details of the original staged recipe.

For the project itself the Windows builds on Travis fail consistently. See e.g. https://travis-ci.org/dabeaz/curio/jobs/534430689.

Is it still worth to keep such project arch-dependent to catch the build errors on some particular platforms? Is an absent package better than a ~broken one?

**Comment by CJ-Wright** [comment]
Hmm, I'm not certain. To some extent this is a question for the curio team.

**Comment by danielballan** [comment]
I vote for (2). The curio code is well separated from the rest of the code, and users have to opt in to invoke it, at which point they could install curio.

To speculate on @mrakitin’s question, I guess  curio is arch-dependent because the exact behavior of I/O calls is arch dependent; for example, the set of available socket options is different.

**Comment by CJ-Wright** [comment]
xref: https://github.com/conda-forge/staged-recipes/issues/4787

**Comment by klauer** [comment]
Curio is now noarch on conda-forge and reportedly working on Windows according to the main repository (https://anaconda.org/conda-forge/curio/files). Closing for now.
